### ISSUE TITLE
Example Code?

### ISSUE THREAD

**Issue by schnorea** [stm32duino/VL53L1X#10]
Any plans to release some examples?

**Comment by cparata** [comment]
Hi @schnorea ,
I do not have plan to add examples because the library is generic enough to be used in whatever board that mounts this component and I do not want to limit the library at any specific board. You can give a look at the examples for the X-NUCLEO-53L1A1 and starting from them derived the examples for your specific platform. Anyway, if you describe your hardware setup, I can help you to write a sketch that works on your specific hardware.
Best Regards,
Carlo
