### ISSUE TITLE
Swipe or left/right detection

### ISSUE THREAD

**Issue by MadTooler** [stm32duino/VL53L1X#9]
Is the functionality to detect left/right swiping with the VL53L1X here as advertised?

Looking through the API User Manual, it is also unclear to me if this functionality is only possible when changing the ROI and making multiple measurements to compare at the cost of time and out of sync measurements, or if there is a way to read in the full array of individual Spad values and process it in the host.

**Comment by cparata** [comment]
Hi @MadTooler ,
the left/write detection is based on [STM32duino Proximity_Gesture library](https://github.com/stm32duino/Proximity_Gesture) and you can give a look at the example that you can find in the [STM32duino X-NUCLEO-53L1A1 library](https://github.com/stm32duino/X-NUCLEO-53L1A1/blob/master/examples/X_NUCLEO_53L1A1_Gesture_DirSwipe/X_NUCLEO_53L1A1_Gesture_DirSwipe.ino) in order to see the APIs and the sensor settings used in this particular use case.
Best Regards,
Carlo

**Comment by MadTooler** [comment]
Carlo,

Thanks for the response and links.  From looking over the noted libraries, it appears the gesture swipe direction detection relies upon multiple sensors.  That is what I expected for the less capable sensors, such as the VL53L0X, but I was hoping to take advantage of the VL53L1X's additional capabilities to measure from varying ROIs to maybe do the same with one sensor.  Are you aware of any examples to achieve gesture detection with this method?

Thank you.

**Comment by cparata** [comment]
Hi @MadTooler ,
in fact you can change the ROI region size before every measurement. Unfortunately, at the moment the ROI region can be set only centered. Anyway, in the next weeks it will be released a new version of the APIs where it will be possible also to change the center position of the ROI region. My concern is about timing. Even if we can change the ROI size and center, we can do it before every consecutive measurement. The minimum timing distance between 2 consecutive measurements is 20ms (the minimum Timing Budget and Interleaved Period). Maybe it will be sufficient to detect slow directional swipe but I do not know if the performance will be acceptable. I will try some experiments when the next release of the APIs will be available. For the moment, if you agree, I will label this issue as "question" because it is not really a bug but it is just a question.
Best Regards,
Carlo

**Comment by MadTooler** [comment]
Carlo,

Thanks for the update.  I am fine with the question label.  Go ahead and close the issue or whatever you prefer.

The timing budget is a bit of concern, yet expected.  My intent is to use the sensor for small robot navigation at low speed.  It may still be effective.  

Thanks.
